spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
spring.rabbitmq.connection-timeout=10000
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=1000
spring.rabbitmq.template.retry.max-attempts=3
spring.rabbitmq.template.retry.multiplier=1.0

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000

spring.application.name=TechaPropioBonosFamiliares
server.servlet.context-path=${CONTEXT_PATH}
server.port=${SERVER_PORT}

# Application Specific Configuration
app.rabbitmq.exchange=${APP_RABBITMQ_EXCHANGE:user-exchange}
app.rabbitmq.queue=${APP_RABBITMQ_QUEUE:email-queue}
app.rabbitmq.routingkey=${APP_RABBITMQ_ROUTINGKEY:email.notification}